- name: multiplay playbook
  hosts: frontend
  tasks:
  - name: debug play01 and task01
    ansible.builtin.debug:
      msg: run play01 and task01

  - name: debug play02 and task02
    ansible.builtin.debug:
      msg: run play02 and task02

- name: multiplay playbook
  hosts: frontend
  tasks:
  - name: debug play01 and task01
    ansible.builtin.debug:
      msg: run play01 and task01

  - name: debug play02 and task02
    ansible.builtin.debug:
      msg: run play02 and task02

