- name: variables declaration
  hosts: local
  connection: local # we are executing this tasks to same ansible server
  vars:
    COURSE: Ansible
    DURATION: 10HRS
    TRAINER: Siva Anna
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} with duration is {{ DURATION }} and the trainer is {{ TRAINER }}."