- name: vars in inventory
  hosts: local
  connection: local
  tasks: 
  - name: vars in inventory
    ansible.builtin.debug:
      msg: "the course is {{ COURSE }},{{ DURATION }},{{ TRAINER }} {{ LEARNER }}."